version: '3.4'

networks:
  aspnetcoreapp-network:
    driver: bridge

services:
  web:
    build:
      context: .
    ports:
        - "56133:80"
        - "44327:443"
    networks:
      - aspnetcoreapp-network
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./dbscripts/init.sql:/docker-entrypoint-initdb.d/init.sql  
    environment:
      # NOTE not to be used like this for real production environment
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass123"
      POSTGRES_DB: "spa_db"
    networks:
      - aspnetcoreapp-network
